import { PrismaClient } from ".prisma/catalog-client";

const prisma = new PrismaClient();

// Imagens via Unsplash Source (uso permitido para desenvolvimento/apresentação)
// Cada URL corresponde a uma foto de produto do tipo indicado.
const products = [
  {
    name: "iPhone 15 Pro",
    description:
      "Smartphone Apple com chip A17 Pro, câmera 48MP e tela Super Retina XDR de 6.1 polegadas.",
    price: 219.9,
    imageUrl: "https://picsum.photos/seed/iphone15pro/400/400",
    category: "Smartphones",
    stock: 50,
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    description:
      "Smartphone Samsung com S Pen integrada, câmera 200MP e tela Dynamic AMOLED de 6.8 polegadas.",
    price: 199.9,
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=400&fit=crop",
    category: "Smartphones",
    stock: 40,
  },
  {
    name: "MacBook Air M3",
    description: "Notebook Apple com chip M3, 16GB RAM, tela Liquid Retina de 13.6 polegadas.",
    price: 349.9,
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop",
    category: "Notebooks",
    stock: 30,
  },
  {
    name: "Dell XPS 15",
    description:
      "Notebook Dell com Intel Core i7, 16GB RAM, tela OLED InfinityEdge de 15.6 polegadas.",
    price: 299.9,
    imageUrl: "https://picsum.photos/seed/dellxps15/400/400",
    category: "Notebooks",
    stock: 25,
  },
  {
    name: "iPad Pro 12.9",
    description:
      "Tablet Apple com chip M2, tela Liquid Retina XDR de 12.9 polegadas, compatível com Apple Pencil.",
    price: 179.9,
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
    category: "Tablets",
    stock: 35,
  },
  {
    name: "AirPods Pro 2",
    description:
      "Fones de ouvido Apple com cancelamento ativo de ruído, áudio adaptativo e estojo MagSafe.",
    price: 49.9,
    imageUrl: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop",
    category: "Acessórios",
    stock: 100,
  },
  {
    name: "Apple Watch Series 9",
    description:
      "Smartwatch Apple com chip S9, tela Always-On Retina, monitoramento de saúde avançado.",
    price: 89.9,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    category: "Wearables",
    stock: 60,
  },
  {
    name: "Sony WH-1000XM5",
    description:
      "Headphone over-ear Sony com cancelamento de ruído líder do mercado e 30h de bateria.",
    price: 59.9,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    category: "Acessórios",
    stock: 45,
  },
  {
    name: "Monitor LG UltraWide 34",
    description: "Monitor ultrawide LG de 34 polegadas, resolução WQHD, painel IPS, USB-C com 90W.",
    price: 129.9,
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop",
    category: "Monitores",
    stock: 20,
  },
  {
    name: "Teclado Mecânico Keychron K8",
    description:
      "Teclado mecânico sem fio Keychron com hot-swap, switches Gateron e retroiluminação RGB.",
    price: 29.9,
    imageUrl: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400&h=400&fit=crop",
    category: "Acessórios",
    stock: 80,
  },
  // +100 produtos (imagens via Picsum com seed único por produto)
  {
    name: "Xiaomi 14",
    description:
      "Smartphone Xiaomi com Snapdragon 8 Gen 3, câmera Leica 50MP e tela AMOLED 6.36 polegadas.",
    price: 189.9,
    imageUrl: "https://picsum.photos/seed/xiaomi14/400/400",
    category: "Smartphones",
    stock: 35,
  },
  {
    name: "Google Pixel 8 Pro",
    description: "Smartphone Google com Tensor G3, câmera 50MP e tela OLED de 6.7 polegadas.",
    price: 209.9,
    imageUrl: "https://picsum.photos/seed/pixel8pro/400/400",
    category: "Smartphones",
    stock: 28,
  },
  {
    name: "Motorola Edge 40",
    description: "Smartphone Motorola com Dimensity 8020, tela pOLED 144Hz e bateria 4600mAh.",
    price: 149.9,
    imageUrl: "https://picsum.photos/seed/motoedge40/400/400",
    category: "Smartphones",
    stock: 42,
  },
  {
    name: "OnePlus 12",
    description:
      "Smartphone OnePlus com Snapdragon 8 Gen 3, câmera Hasselblad e carregamento 100W.",
    price: 199.9,
    imageUrl: "https://picsum.photos/seed/oneplus12/400/400",
    category: "Smartphones",
    stock: 30,
  },
  {
    name: "Nothing Phone (2)",
    description: "Smartphone Nothing com Snapdragon 8+ Gen 1 e design Glyph Interface com LEDs.",
    price: 179.9,
    imageUrl: "https://picsum.photos/seed/nothing2/400/400",
    category: "Smartphones",
    stock: 25,
  },
  {
    name: "ASUS ROG Phone 8",
    description: "Smartphone gamer ASUS com Snapdragon 8 Gen 3, tela AMOLED 165Hz e 6000mAh.",
    price: 249.9,
    imageUrl: "https://picsum.photos/seed/rogphone8/400/400",
    category: "Smartphones",
    stock: 18,
  },
  {
    name: "Realme GT 5",
    description: "Smartphone Realme com Snapdragon 8 Gen 2 e carregamento 240W SuperVOOC.",
    price: 159.9,
    imageUrl: "https://picsum.photos/seed/realmegt5/400/400",
    category: "Smartphones",
    stock: 38,
  },
  {
    name: "iPhone 14",
    description:
      "Smartphone Apple com chip A15 Bionic, câmera dupla 12MP e tela Super Retina XDR 6.1.",
    price: 169.9,
    imageUrl: "https://picsum.photos/seed/iphone14/400/400",
    category: "Smartphones",
    stock: 55,
  },
  {
    name: "Samsung Galaxy A54",
    description:
      "Smartphone Samsung intermediário com Exynos 1380, tela Super AMOLED e câmera 50MP.",
    price: 129.9,
    imageUrl: "https://picsum.photos/seed/galaxya54/400/400",
    category: "Smartphones",
    stock: 60,
  },
  {
    name: "Poco F5 Pro",
    description: "Smartphone Poco com Snapdragon 8+ Gen 1, tela AMOLED 120Hz e 5160mAh.",
    price: 139.9,
    imageUrl: "https://picsum.photos/seed/pocof5pro/400/400",
    category: "Smartphones",
    stock: 45,
  },
  {
    name: "Lenovo ThinkPad X1 Carbon",
    description:
      "Notebook empresarial Lenovo com Intel Core i7, 16GB RAM, tela 14 polegadas e 12h de bateria.",
    price: 399.9,
    imageUrl: "https://picsum.photos/seed/thinkpadx1/400/400",
    category: "Notebooks",
    stock: 22,
  },
  {
    name: "HP Pavilion 15",
    description: "Notebook HP com AMD Ryzen 5, 8GB RAM, SSD 256GB e tela Full HD 15.6.",
    price: 229.9,
    imageUrl: "https://picsum.photos/seed/hppavilion15/400/400",
    category: "Notebooks",
    stock: 35,
  },
  {
    name: "Acer Swift 3",
    description: "Notebook ultrafino Acer com Intel Core i5, 8GB RAM e peso 1.2kg.",
    price: 199.9,
    imageUrl: "https://picsum.photos/seed/acerswift3/400/400",
    category: "Notebooks",
    stock: 28,
  },
  {
    name: "ASUS ZenBook 14",
    description: "Notebook ASUS com Intel Core i7, tela NanoEdge e design compacto.",
    price: 279.9,
    imageUrl: "https://picsum.photos/seed/zenbook14/400/400",
    category: "Notebooks",
    stock: 20,
  },
  {
    name: "MacBook Pro 14 M3 Pro",
    description: "Notebook Apple com chip M3 Pro, 18GB RAM e tela Liquid Retina XDR 14.2.",
    price: 449.9,
    imageUrl: "https://picsum.photos/seed/mbp14m3/400/400",
    category: "Notebooks",
    stock: 15,
  },
  {
    name: "Microsoft Surface Laptop 5",
    description: "Notebook Microsoft com Intel Core i5, tela PixelSense 13.5 e touchscreen.",
    price: 329.9,
    imageUrl: "https://picsum.photos/seed/surfacelap5/400/400",
    category: "Notebooks",
    stock: 18,
  },
  {
    name: "LG Gram 17",
    description: "Notebook ultraleve LG 17 polegadas com peso 1.35kg e bateria de longa duração.",
    price: 319.9,
    imageUrl: "https://picsum.photos/seed/lggram17/400/400",
    category: "Notebooks",
    stock: 12,
  },
  {
    name: "Razer Blade 15",
    description: "Notebook gamer Razer com RTX 4070, Intel i7 e tela 240Hz.",
    price: 499.9,
    imageUrl: "https://picsum.photos/seed/razerblade15/400/400",
    category: "Notebooks",
    stock: 10,
  },
  {
    name: "MSI Katana 15",
    description: "Notebook gamer MSI com RTX 4060, Intel i5 e tela 144Hz.",
    price: 349.9,
    imageUrl: "https://picsum.photos/seed/msikatana15/400/400",
    category: "Notebooks",
    stock: 25,
  },
  {
    name: "Samsung Galaxy Book3",
    description: "Notebook Samsung com Intel Core i7, tela AMOLED e S Pen incluído.",
    price: 289.9,
    imageUrl: "https://picsum.photos/seed/galaxybook3/400/400",
    category: "Notebooks",
    stock: 16,
  },
  {
    name: "Samsung Galaxy Tab S9",
    description: "Tablet Samsung com Snapdragon 8 Gen 2, tela Dynamic AMOLED 120Hz e S Pen.",
    price: 199.9,
    imageUrl: "https://picsum.photos/seed/tabs9/400/400",
    category: "Tablets",
    stock: 32,
  },
  {
    name: "iPad Air 5",
    description: "Tablet Apple com chip M1, tela Liquid Retina 10.9 e suporte a Magic Keyboard.",
    price: 149.9,
    imageUrl: "https://picsum.photos/seed/ipadair5/400/400",
    category: "Tablets",
    stock: 40,
  },
  {
    name: "iPad Mini 6",
    description: "Tablet compacto Apple com chip A15 Bionic e tela 8.3 polegadas.",
    price: 119.9,
    imageUrl: "https://picsum.photos/seed/ipadmini6/400/400",
    category: "Tablets",
    stock: 45,
  },
  {
    name: "Lenovo Tab P12",
    description: "Tablet Lenovo 12.7 polegadas com Snapdragon 685 e 8GB RAM.",
    price: 139.9,
    imageUrl: "https://picsum.photos/seed/tabp12/400/400",
    category: "Tablets",
    stock: 28,
  },
  {
    name: "Xiaomi Pad 6",
    description: "Tablet Xiaomi com Snapdragon 870, tela 11 polegadas 144Hz e 8840mAh.",
    price: 129.9,
    imageUrl: "https://picsum.photos/seed/mipad6/400/400",
    category: "Tablets",
    stock: 35,
  },
  {
    name: "Amazon Fire HD 10",
    description: "Tablet Amazon com tela 10.1 polegadas, 3GB RAM e 13h de bateria.",
    price: 79.9,
    imageUrl: "https://picsum.photos/seed/firehd10/400/400",
    category: "Tablets",
    stock: 55,
  },
  {
    name: "Microsoft Surface Go 3",
    description: "Tablet Windows com Intel Pentium, 8GB RAM e suporte a Type Cover.",
    price: 169.9,
    imageUrl: "https://picsum.photos/seed/surfacego3/400/400",
    category: "Tablets",
    stock: 22,
  },
  {
    name: "OnePlus Pad",
    description: "Tablet OnePlus com Dimensity 9000, tela 11.6 144Hz e 9510mAh.",
    price: 179.9,
    imageUrl: "https://picsum.photos/seed/onepluspad/400/400",
    category: "Tablets",
    stock: 20,
  },
  {
    name: "Realme Pad 2",
    description: "Tablet Realme com Helio G99, tela 11.5 e 8360mAh.",
    price: 99.9,
    imageUrl: "https://picsum.photos/seed/realmpad2/400/400",
    category: "Tablets",
    stock: 42,
  },
  {
    name: "Oppo Pad 2",
    description: "Tablet Oppo com Dimensity 9000 e tela 11.61 polegadas 144Hz.",
    price: 159.9,
    imageUrl: "https://picsum.photos/seed/oppopad2/400/400",
    category: "Tablets",
    stock: 25,
  },
  {
    name: "JBL Tune 510BT",
    description: "Fone de ouvido Bluetooth JBL com 40h de bateria e dobra para transporte.",
    price: 34.9,
    imageUrl: "https://picsum.photos/seed/jbl510/400/400",
    category: "Acessórios",
    stock: 90,
  },
  {
    name: "JBL Flip 6",
    description: "Caixa de som portátil JBL à prova d'água com som stereo e 12h de bateria.",
    price: 79.9,
    imageUrl: "https://picsum.photos/seed/jblflip6/400/400",
    category: "Acessórios",
    stock: 65,
  },
  {
    name: "Samsung Galaxy Buds2 Pro",
    description: "Fones true wireless Samsung com ANC e áudio 360.",
    price: 69.9,
    imageUrl: "https://picsum.photos/seed/buds2pro/400/400",
    category: "Acessórios",
    stock: 70,
  },
  {
    name: "Sony LinkBuds S",
    description: "Fones true wireless Sony com cancelamento de ruído e 20h de bateria total.",
    price: 89.9,
    imageUrl: "https://picsum.photos/seed/linkbudss/400/400",
    category: "Acessórios",
    stock: 48,
  },
  {
    name: "Bose QC Ultra",
    description: "Fone over-ear Bose com cancelamento de ruído adaptativo e áudio espacial.",
    price: 199.9,
    imageUrl: "https://picsum.photos/seed/boseqcultra/400/400",
    category: "Acessórios",
    stock: 30,
  },
  {
    name: "Anker Soundcore Life Q35",
    description: "Fone Bluetooth Anker com ANC híbrido e 40h de reprodução.",
    price: 49.9,
    imageUrl: "https://picsum.photos/seed/soundcoreq35/400/400",
    category: "Acessórios",
    stock: 85,
  },
  {
    name: "Xiaomi Mi Power Bank 3",
    description: "Power bank Xiaomi 20000mAh com carregamento rápido 18W e duas portas USB.",
    price: 29.9,
    imageUrl: "https://picsum.photos/seed/mipowerbank3/400/400",
    category: "Acessórios",
    stock: 120,
  },
  {
    name: "Baseus Blade 100W",
    description: "Carregador GaN Baseus 100W com 4 portas e cabo USB-C incluído.",
    price: 44.9,
    imageUrl: "https://picsum.photos/seed/baseusblade/400/400",
    category: "Acessórios",
    stock: 75,
  },
  {
    name: "Capa iPhone 15 Silicone",
    description: "Capa de silicone oficial Apple para iPhone 15, diversas cores.",
    price: 24.9,
    imageUrl: "https://picsum.photos/seed/capaiphone15/400/400",
    category: "Acessórios",
    stock: 200,
  },
  {
    name: "Película Vidro Samsung S24",
    description: "Película de vidro temperado para Samsung Galaxy S24, proteção 9H.",
    price: 14.9,
    imageUrl: "https://picsum.photos/seed/peliculas24/400/400",
    category: "Acessórios",
    stock: 150,
  },
  {
    name: "Apple Watch Ultra 2",
    description: "Smartwatch Apple para esportes com GPS preciso, 49mm e 36h de bateria.",
    price: 149.9,
    imageUrl: "https://picsum.photos/seed/watchultra2/400/400",
    category: "Wearables",
    stock: 35,
  },
  {
    name: "Samsung Galaxy Watch 6",
    description: "Smartwatch Samsung com Wear OS, monitor de sono e BIA.",
    price: 99.9,
    imageUrl: "https://picsum.photos/seed/galaxywatch6/400/400",
    category: "Wearables",
    stock: 50,
  },
  {
    name: "Garmin Forerunner 265",
    description: "Relógio Garmin para corrida com AMOLED e métricas de treino.",
    price: 179.9,
    imageUrl: "https://picsum.photos/seed/forerunner265/400/400",
    category: "Wearables",
    stock: 28,
  },
  {
    name: "Amazfit GTR 4",
    description: "Smartwatch Amazfit com GPS dual-band e bateria de até 14 dias.",
    price: 79.9,
    imageUrl: "https://picsum.photos/seed/gtr4/400/400",
    category: "Wearables",
    stock: 45,
  },
  {
    name: "Xiaomi Band 8 Pro",
    description: "Pulseira Xiaomi com tela AMOLED 1.74 e mais de 14 dias de bateria.",
    price: 39.9,
    imageUrl: "https://picsum.photos/seed/band8pro/400/400",
    category: "Wearables",
    stock: 95,
  },
  {
    name: "Fitbit Charge 6",
    description: "Tracker Fitbit com ECG, monitor de estresse e Google Maps.",
    price: 69.9,
    imageUrl: "https://picsum.photos/seed/charge6/400/400",
    category: "Wearables",
    stock: 60,
  },
  {
    name: "Huawei Watch GT 4",
    description: "Smartwatch Huawei com design clássico e até 14 dias de bateria.",
    price: 89.9,
    imageUrl: "https://picsum.photos/seed/watchgt4/400/400",
    category: "Wearables",
    stock: 38,
  },
  {
    name: "Oppo Watch 4 Pro",
    description: "Smartwatch Oppo com Snapdragon W5 e Wear OS.",
    price: 119.9,
    imageUrl: "https://picsum.photos/seed/oppowatch4/400/400",
    category: "Wearables",
    stock: 25,
  },
  {
    name: "Monitor Samsung Odyssey G7",
    description: "Monitor gaming Samsung 32 polegadas curvo 1000R, 240Hz e QLED.",
    price: 279.9,
    imageUrl: "https://picsum.photos/seed/odysseyg7/400/400",
    category: "Monitores",
    stock: 22,
  },
  {
    name: "Monitor Dell S2722DGM",
    description: "Monitor Dell 27 polegadas curvo 165Hz, VA e FreeSync Premium.",
    price: 189.9,
    imageUrl: "https://picsum.photos/seed/dells2722/400/400",
    category: "Monitores",
    stock: 35,
  },
  {
    name: "LG 27GP850-B",
    description: "Monitor LG 27 polegadas Nano IPS 165Hz, 1ms e G-Sync.",
    price: 229.9,
    imageUrl: "https://picsum.photos/seed/lg27gp850/400/400",
    category: "Monitores",
    stock: 28,
  },
  {
    name: "ASUS ProArt PA278QV",
    description: "Monitor profissional ASUS 27 polegadas IPS, calibração de fábrica e USB-C.",
    price: 199.9,
    imageUrl: "https://picsum.photos/seed/proart278/400/400",
    category: "Monitores",
    stock: 20,
  },
  {
    name: "BenQ PD2705U",
    description: "Monitor 4K BenQ 27 polegadas para design e vídeo.",
    price: 349.9,
    imageUrl: "https://picsum.photos/seed/benqpd2705/400/400",
    category: "Monitores",
    stock: 15,
  },
  {
    name: "AOC 24G2",
    description: "Monitor AOC 24 polegadas IPS 144Hz e FreeSync.",
    price: 119.9,
    imageUrl: "https://picsum.photos/seed/aoc24g2/400/400",
    category: "Monitores",
    stock: 55,
  },
  {
    name: "MSI Optix G241",
    description: "Monitor MSI 24 polegadas 144Hz IPS e painel sem bordas.",
    price: 129.9,
    imageUrl: "https://picsum.photos/seed/optixg241/400/400",
    category: "Monitores",
    stock: 42,
  },
  {
    name: "ViewSonic VX2768-2KPC",
    description: "Monitor ViewSonic 27 polegadas 2K 165Hz curvo.",
    price: 159.9,
    imageUrl: "https://picsum.photos/seed/vx2768/400/400",
    category: "Monitores",
    stock: 30,
  },
  {
    name: "Gigabyte M28U",
    description: "Monitor Gigabyte 28 polegadas 4K 144Hz com HDMI 2.1.",
    price: 299.9,
    imageUrl: "https://picsum.photos/seed/m28u/400/400",
    category: "Monitores",
    stock: 18,
  },
  {
    name: "Mouse Logitech MX Master 3S",
    description: "Mouse ergonômico Logitech com sensor 8K DPI e scroll ultrarrápido.",
    price: 59.9,
    imageUrl: "https://picsum.photos/seed/mxmaster3s/400/400",
    category: "Periféricos",
    stock: 70,
  },
  {
    name: "Mouse Razer DeathAdder V3",
    description: "Mouse gamer Razer com sensor Focus Pro 30K e 90g.",
    price: 49.9,
    imageUrl: "https://picsum.photos/seed/deathadderv3/400/400",
    category: "Periféricos",
    stock: 65,
  },
  {
    name: "Teclado Logitech G Pro X",
    description: "Teclado gamer Logitech com switches hot-swap e RGB.",
    price: 79.9,
    imageUrl: "https://picsum.photos/seed/gprox/400/400",
    category: "Periféricos",
    stock: 45,
  },
  {
    name: "Webcam Logitech C920",
    description: "Webcam Full HD 1080p Logitech com microfone integrado.",
    price: 44.9,
    imageUrl: "https://picsum.photos/seed/c920/400/400",
    category: "Periféricos",
    stock: 80,
  },
  {
    name: "Headset HyperX Cloud II",
    description: "Headset gamer HyperX com som 7.1 virtual e microfone removível.",
    price: 54.9,
    imageUrl: "https://picsum.photos/seed/cloud2/400/400",
    category: "Periféricos",
    stock: 55,
  },
  {
    name: "SSD Samsung 990 Pro 1TB",
    description: "SSD NVMe Samsung 1TB PCIe 4.0 com até 7450 MB/s leitura.",
    price: 89.9,
    imageUrl: "https://picsum.photos/seed/990pro/400/400",
    category: "Armazenamento",
    stock: 90,
  },
  {
    name: "SSD WD Black SN850X 2TB",
    description: "SSD NVMe WD Black 2TB com heatsink e 7300 MB/s.",
    price: 149.9,
    imageUrl: "https://picsum.photos/seed/sn850x/400/400",
    category: "Armazenamento",
    stock: 45,
  },
  {
    name: "HD Externo Seagate 2TB",
    description: "HD externo portátil Seagate 2TB USB 3.0 para backup.",
    price: 59.9,
    imageUrl: "https://picsum.photos/seed/seagate2tb/400/400",
    category: "Armazenamento",
    stock: 70,
  },
  {
    name: "Pen Drive SanDisk 128GB",
    description: "Pen drive SanDisk Ultra 128GB USB 3.2.",
    price: 19.9,
    imageUrl: "https://picsum.photos/seed/sandisk128/400/400",
    category: "Armazenamento",
    stock: 150,
  },
  {
    name: "Cartão MicroSD Samsung 256GB",
    description: "Cartão Samsung EVO Plus 256GB U3 para câmeras e celulares.",
    price: 29.9,
    imageUrl: "https://picsum.photos/seed/evoplus256/400/400",
    category: "Armazenamento",
    stock: 120,
  },
  {
    name: "Roteador TP-Link Archer AX73",
    description: "Roteador Wi-Fi 6 TP-Link dual-band com 5 Gbps e 4 antenas.",
    price: 79.9,
    imageUrl: "https://picsum.photos/seed/ax73/400/400",
    category: "Redes",
    stock: 40,
  },
  {
    name: "Mesh Deco X20",
    description: "Sistema mesh TP-Link 2 unidades Wi-Fi 6 para cobertura ampla.",
    price: 99.9,
    imageUrl: "https://picsum.photos/seed/decox20/400/400",
    category: "Redes",
    stock: 35,
  },
  {
    name: "Adaptador USB-C Hub 7 em 1",
    description: "Hub USB-C com HDMI, USB 3.0, leitor SD e PD 100W.",
    price: 34.9,
    imageUrl: "https://picsum.photos/seed/hub7em1/400/400",
    category: "Acessórios",
    stock: 95,
  },
  {
    name: "Suporte para Notebook",
    description: "Suporte ergonômico de alumínio para notebook com ventilação.",
    price: 24.9,
    imageUrl: "https://picsum.photos/seed/suportenotebook/400/400",
    category: "Acessórios",
    stock: 110,
  },
  {
    name: "Luminária LED de Mesa",
    description: "Luminária LED com regulagem de brilho e temperatura de cor.",
    price: 39.9,
    imageUrl: "https://picsum.photos/seed/luminarialed/400/400",
    category: "Acessórios",
    stock: 75,
  },
  {
    name: "Cadeira Gamer DXRacer",
    description: "Cadeira gamer DXRacer com apoio lombar e reclinação 180°.",
    price: 249.9,
    imageUrl: "https://picsum.photos/seed/dxracer/400/400",
    category: "Acessórios",
    stock: 25,
  },
  {
    name: "Mesa Gamer 1.40m",
    description: "Mesa para gaming 1.40m com tampo em MDF e estrutura em aço.",
    price: 149.9,
    imageUrl: "https://picsum.photos/seed/mesagamer/400/400",
    category: "Acessórios",
    stock: 30,
  },
  {
    name: "Kindle Paperwhite",
    description: "Leitor Kindle 6.8 polegadas com luz quente e à prova d'água.",
    price: 89.9,
    imageUrl: "https://picsum.photos/seed/paperwhite/400/400",
    category: "E-readers",
    stock: 60,
  },
  {
    name: "Kobo Libra 2",
    description: "E-reader Kobo 7 polegadas com botões de virada e à prova d'água.",
    price: 79.9,
    imageUrl: "https://picsum.photos/seed/kobolibra2/400/400",
    category: "E-readers",
    stock: 40,
  },
  {
    name: "Echo Dot 5",
    description: "Alto-falante inteligente Amazon com Alexa e relógio.",
    price: 34.9,
    imageUrl: "https://picsum.photos/seed/echodot5/400/400",
    category: "Smart Home",
    stock: 85,
  },
  {
    name: "Google Nest Mini",
    description: "Alto-falante Google com assistente e som melhorado.",
    price: 29.9,
    imageUrl: "https://picsum.photos/seed/nestmini/400/400",
    category: "Smart Home",
    stock: 90,
  },
  {
    name: "Ring Video Doorbell",
    description: "Campainha inteligente Ring com câmera 1080p e visão noturna.",
    price: 59.9,
    imageUrl: "https://picsum.photos/seed/ringdoorbell/400/400",
    category: "Smart Home",
    stock: 50,
  },
  {
    name: "Philips Hue Bridge",
    description: "Bridge Philips Hue para controle de até 50 lâmpadas inteligentes.",
    price: 44.9,
    imageUrl: "https://picsum.photos/seed/huebridge/400/400",
    category: "Smart Home",
    stock: 55,
  },
  {
    name: "Apple TV 4K",
    description: "Streaming Apple TV 4K com chip A15 e suporte a HDR10+ e Dolby Vision.",
    price: 129.9,
    imageUrl: "https://picsum.photos/seed/appletv4k/400/400",
    category: "Streaming",
    stock: 45,
  },
  {
    name: "Chromecast com Google TV",
    description: "Streaming Google TV 4K com controle por voz e Google Assistant.",
    price: 49.9,
    imageUrl: "https://picsum.photos/seed/chromecast/400/400",
    category: "Streaming",
    stock: 70,
  },
  {
    name: "Fire TV Stick 4K Max",
    description: "Stick Amazon 4K com Wi-Fi 6 e Alexa.",
    price: 39.9,
    imageUrl: "https://picsum.photos/seed/firestick4k/400/400",
    category: "Streaming",
    stock: 95,
  },
  {
    name: "Roku Streaming Stick+",
    description: "Stick Roku 4K HDR com controle por voz e privacidade.",
    price: 34.9,
    imageUrl: "https://picsum.photos/seed/rokustick/400/400",
    category: "Streaming",
    stock: 65,
  },
  {
    name: "Nintendo Switch OLED",
    description: "Console Nintendo Switch com tela OLED 7 polegadas e 64GB.",
    price: 249.9,
    imageUrl: "https://picsum.photos/seed/switcholed/400/400",
    category: "Consoles",
    stock: 35,
  },
  {
    name: "PlayStation 5 Slim",
    description: "Console Sony PS5 Slim com 1TB SSD e leitor de disco opcional.",
    price: 349.9,
    imageUrl: "https://picsum.photos/seed/ps5slim/400/400",
    category: "Consoles",
    stock: 28,
  },
  {
    name: "Xbox Series S",
    description: "Console Microsoft Xbox Series S 512GB para jogos digitais.",
    price: 199.9,
    imageUrl: "https://picsum.photos/seed/xboxs/400/400",
    category: "Consoles",
    stock: 42,
  },
  {
    name: "Steam Deck 256GB",
    description: "Handheld Valve Steam Deck com tela 7 polegadas e 256GB NVMe.",
    price: 279.9,
    imageUrl: "https://picsum.photos/seed/steamdeck/400/400",
    category: "Consoles",
    stock: 22,
  },
  {
    name: "Controle DualSense",
    description: "Controle PlayStation 5 DualSense com haptic feedback e microfone.",
    price: 59.9,
    imageUrl: "https://picsum.photos/seed/dualsense/400/400",
    category: "Consoles",
    stock: 80,
  },
  {
    name: "Controle Xbox Wireless",
    description: "Controle Xbox Series com Bluetooth e compartilhamento.",
    price: 49.9,
    imageUrl: "https://picsum.photos/seed/xboxctrl/400/400",
    category: "Consoles",
    stock: 75,
  },
  {
    name: "Câmera GoPro Hero 12",
    description: "Action cam GoPro 5.3K com HyperSmooth 6.0 e à prova d'água.",
    price: 199.9,
    imageUrl: "https://picsum.photos/seed/hero12/400/400",
    category: "Câmeras",
    stock: 30,
  },
  {
    name: "DJI Mini 3 Pro",
    description: "Drone DJI Mini 3 Pro com câmera 4K e 34 min de voo.",
    price: 449.9,
    imageUrl: "https://picsum.photos/seed/mini3pro/400/400",
    category: "Câmeras",
    stock: 18,
  },
  {
    name: "Kindle Scribe",
    description: "E-reader e tablet para notas Amazon com caneta e tela 10.2.",
    price: 199.9,
    imageUrl: "https://picsum.photos/seed/scribes/400/400",
    category: "E-readers",
    stock: 25,
  },
  {
    name: "Repelente de Mosquitos UV",
    description: "Aparelho repelente de insetos com luz UV e grade elétrica.",
    price: 24.9,
    imageUrl: "https://picsum.photos/seed/repelenteuv/400/400",
    category: "Smart Home",
    stock: 60,
  },
  {
    name: "Smartwatch Kids X6",
    description: "Relógio infantil com câmera, chamadas e GPS para crianças.",
    price: 44.9,
    imageUrl: "https://picsum.photos/seed/watchkids/400/400",
    category: "Wearables",
    stock: 55,
  },
  {
    name: "Fita LED 5m RGB",
    description: "Fita de LED RGB 5 metros com controle por app e 16 milhões de cores.",
    price: 29.9,
    imageUrl: "https://picsum.photos/seed/fitaled/400/400",
    category: "Acessórios",
    stock: 100,
  },
  {
    name: "Organizador de Cabos",
    description: "Kit organizador de cabos com braçadeiras e etiquetas.",
    price: 14.9,
    imageUrl: "https://picsum.photos/seed/orgcabos/400/400",
    category: "Acessórios",
    stock: 130,
  },
  {
    name: "Cooler para Notebook",
    description: "Base refrigerada para notebook com 5 ventoinhas USB.",
    price: 34.9,
    imageUrl: "https://picsum.photos/seed/coolernote/400/400",
    category: "Acessórios",
    stock: 70,
  },
  {
    name: "Suporte para Monitor",
    description: "Braço articulado para monitor com VESA 75/100.",
    price: 49.9,
    imageUrl: "https://picsum.photos/seed/bracomonitor/400/400",
    category: "Acessórios",
    stock: 45,
  },
  {
    name: "Teclado Numérico USB",
    description: "Teclado numérico separado com teclas de cálculo.",
    price: 19.9,
    imageUrl: "https://picsum.photos/seed/tecladonum/400/400",
    category: "Periféricos",
    stock: 85,
  },
  {
    name: "Mouse Pad XXL",
    description: "Mouse pad estendido 90x40cm com base antiderrapante.",
    price: 24.9,
    imageUrl: "https://picsum.photos/seed/mousepadxxl/400/400",
    category: "Periféricos",
    stock: 95,
  },
  {
    name: "Switch HDMI 4K 3 portas",
    description: "Seletor HDMI 4K 60Hz com 3 entradas e 1 saída.",
    price: 29.9,
    imageUrl: "https://picsum.photos/seed/hdmiswitch/400/400",
    category: "Acessórios",
    stock: 65,
  },
  {
    name: "Cabo USB-C 2m 100W",
    description: "Cabo USB-C nylon 2 metros com suporte a 100W e dados.",
    price: 18.9,
    imageUrl: "https://picsum.photos/seed/cabousbc/400/400",
    category: "Acessórios",
    stock: 140,
  },
  {
    name: "Carregador Magsafe",
    description: "Carregador magnético Magsafe compatível com iPhone 12 e posteriores.",
    price: 22.9,
    imageUrl: "https://picsum.photos/seed/magsafe/400/400",
    category: "Acessórios",
    stock: 115,
  },
  {
    name: "Suporte para Celular",
    description: "Suporte para celular no carro com ajuste de ângulo.",
    price: 14.9,
    imageUrl: "https://picsum.photos/seed/suportecel/400/400",
    category: "Acessórios",
    stock: 125,
  },
  {
    name: "Fone de Ouvido com Fio",
    description: "Fone de ouvido intra-auricular com microfone e controle inline.",
    price: 24.9,
    imageUrl: "https://picsum.photos/seed/fonefio/400/400",
    category: "Acessórios",
    stock: 160,
  },
  {
    name: "Alto-falante Bluetooth Mini",
    description: "Alto-falante portátil Bluetooth com 10h de bateria.",
    price: 29.9,
    imageUrl: "https://picsum.photos/seed/speakerbt/400/400",
    category: "Acessórios",
    stock: 88,
  },
  {
    name: "Ring Light 10 polegadas",
    description: "Luz de ring LED 10 polegadas com tripé para streaming e vídeo.",
    price: 39.9,
    imageUrl: "https://picsum.photos/seed/ringlight/400/400",
    category: "Acessórios",
    stock: 52,
  },
  {
    name: "Tripé para Celular",
    description: "Tripé flexível para celular com adaptador universal.",
    price: 19.9,
    imageUrl: "https://picsum.photos/seed/tripecel/400/400",
    category: "Acessórios",
    stock: 98,
  },
  {
    name: "Câmera Web 4K",
    description: "Webcam 4K com autofoco e microfone com redução de ruído.",
    price: 89.9,
    imageUrl: "https://picsum.photos/seed/webcam4k/400/400",
    category: "Periféricos",
    stock: 38,
  },
  {
    name: "Impressora Epson EcoTank",
    description: "Impressora multifuncional Epson com tanque de tinta e baixo custo por página.",
    price: 179.9,
    imageUrl: "https://picsum.photos/seed/ecotank/400/400",
    category: "Periféricos",
    stock: 28,
  },
  {
    name: "Scanner Documentos A4",
    description: "Scanner de documentos A4 com alimentador e 600 DPI.",
    price: 69.9,
    imageUrl: "https://picsum.photos/seed/scannera4/400/400",
    category: "Periféricos",
    stock: 42,
  },
  {
    name: "Roteador 5G CPE",
    description: "Roteador 5G indoor com Wi-Fi 6 e SIM integrado.",
    price: 149.9,
    imageUrl: "https://picsum.photos/seed/cpe5g/400/400",
    category: "Redes",
    stock: 22,
  },
  {
    name: "Placa de Rede Wi-Fi 6",
    description: "Placa PCIe Wi-Fi 6 para desktop com Bluetooth 5.2.",
    price: 34.9,
    imageUrl: "https://picsum.photos/seed/placawifi6/400/400",
    category: "Redes",
    stock: 58,
  },
  {
    name: "NAS Synology 2 Bay",
    description: "NAS Synology 2 bays para armazenamento em rede e backup.",
    price: 229.9,
    imageUrl: "https://picsum.photos/seed/synology2/400/400",
    category: "Armazenamento",
    stock: 20,
  },
  {
    name: "Dock Station USB-C",
    description: "Dock station USB-C com 2 monitores 4K, Ethernet e 85W PD.",
    price: 129.9,
    imageUrl: "https://picsum.photos/seed/dockusbc/400/400",
    category: "Acessórios",
    stock: 35,
  },
  {
    name: "Gravador de Áudio USB",
    description: "Interface de áudio USB para podcast e streaming com phantom.",
    price: 79.9,
    imageUrl: "https://picsum.photos/seed/gravadorusb/400/400",
    category: "Periféricos",
    stock: 32,
  },
  {
    name: "Microfone Condensador",
    description: "Microfone condensador para estúdio com suporte e cabo XLR.",
    price: 54.9,
    imageUrl: "https://picsum.photos/seed/miccond/400/400",
    category: "Periféricos",
    stock: 48,
  },
  {
    name: "Luminária de Mesa USB",
    description: "Luminária de mesa LED com carregador USB e 3 níveis de brilho.",
    price: 27.9,
    imageUrl: "https://picsum.photos/seed/lummesa/400/400",
    category: "Acessórios",
    stock: 72,
  },
  {
    name: "Projetor Mini LED",
    description: "Projetor portátil Full HD com Android TV e 4h de bateria.",
    price: 199.9,
    imageUrl: "https://picsum.photos/seed/projetormini/400/400",
    category: "Monitores",
    stock: 25,
  },
  {
    name: "Barra de Som 2.1",
    description: "Barra de som 2.1 canais com subwoofer e Bluetooth.",
    price: 89.9,
    imageUrl: "https://picsum.photos/seed/barra21/400/400",
    category: "Acessórios",
    stock: 40,
  },
  {
    name: "Controle Remoto Universal",
    description: "Controle remoto universal programável para TV, ar e streaming.",
    price: 19.9,
    imageUrl: "https://picsum.photos/seed/controleuniv/400/400",
    category: "Smart Home",
    stock: 65,
  },
  {
    name: "Sensor de Presença",
    description: "Sensor de presença PIR para automação e economia de energia.",
    price: 24.9,
    imageUrl: "https://picsum.photos/seed/sensorpresenca/400/400",
    category: "Smart Home",
    stock: 55,
  },
  {
    name: "Fechadura Inteligente",
    description: "Fechadura digital com impressão digital e app.",
    price: 149.9,
    imageUrl: "https://picsum.photos/seed/fechadura/400/400",
    category: "Smart Home",
    stock: 22,
  },
  {
    name: "Robô Aspirador",
    description: "Robô aspirador com mapeamento a laser e app.",
    price: 279.9,
    imageUrl: "https://picsum.photos/seed/roboaspirador/400/400",
    category: "Smart Home",
    stock: 18,
  },
  {
    name: "Smart TV 43 polegadas",
    description: "Smart TV Full HD 43 polegadas com Android TV e Chromecast built-in.",
    price: 249.9,
    imageUrl: "https://picsum.photos/seed/smartv43/400/400",
    category: "TV",
    stock: 30,
  },
  {
    name: "Soundbar 3.1 canais",
    description: "Soundbar com subwoofer sem fio e Dolby Digital.",
    price: 129.9,
    imageUrl: "https://picsum.photos/seed/soundbar31/400/400",
    category: "Acessórios",
    stock: 45,
  },
  {
    name: "Fone Bluetooth Esportivo",
    description: "Fone de ouvido esportivo à prova d'água com 12h de bateria.",
    price: 44.9,
    imageUrl: "https://picsum.photos/seed/foneesportivo/400/400",
    category: "Acessórios",
    stock: 78,
  },
  {
    name: "Carregador Portátil 10000mAh",
    description: "Power bank 10000mAh com duas portas USB e indicador LED.",
    price: 22.9,
    imageUrl: "https://picsum.photos/seed/power10k/400/400",
    category: "Acessórios",
    stock: 135,
  },
  {
    name: "Suporte para Tablet",
    description: "Suporte ajustável para tablet com base pesada e rotação 360°.",
    price: 27.9,
    imageUrl: "https://picsum.photos/seed/suportetablet/400/400",
    category: "Acessórios",
    stock: 62,
  },
  {
    name: "Cabo HDMI 2.1 2m",
    description: "Cabo HDMI 2.1 certificado para 4K 120Hz e 8K.",
    price: 24.9,
    imageUrl: "https://picsum.photos/seed/hdmi21/400/400",
    category: "Acessórios",
    stock: 105,
  },
  {
    name: "Hub USB 3.0 4 portas",
    description: "Hub USB 3.0 com 4 portas e alimentação externa.",
    price: 19.9,
    imageUrl: "https://picsum.photos/seed/hubusb4/400/400",
    category: "Acessórios",
    stock: 115,
  },
  {
    name: "Tapete de Mouse RGB",
    description: "Mouse pad gamer com borda RGB e superfície de tecido.",
    price: 29.9,
    imageUrl: "https://picsum.photos/seed/mousepadrgb/400/400",
    category: "Periféricos",
    stock: 68,
  },
  {
    name: "Suporte para Celular Veicular",
    description: "Suporte magnético para celular no carro com base em ar condicionado.",
    price: 16.9,
    imageUrl: "https://picsum.photos/seed/suportecelcar/400/400",
    category: "Acessórios",
    stock: 92,
  },
  {
    name: "Fonte Notebook 65W",
    description: "Fonte universal 65W USB-C com múltiplas pontas para notebooks.",
    price: 34.9,
    imageUrl: "https://picsum.photos/seed/fonte65w/400/400",
    category: "Acessórios",
    stock: 58,
  },
];

async function main() {
  console.log("Seeding database...");

  await prisma.product.deleteMany();

  const result = await prisma.product.createMany({ data: products });

  console.log(`Seed complete. Inserted ${result.count} products.`);
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
